name: "Action"
on:
  pull_request:
    branches:
      - master
    paths:
      - 'vars/project-1/c1.txt'
  push:
    branches:
      - master
    paths:
      - 'vars/project-1/c1.txt'
env:
  Project_Id: project-1
  Cluster_name: c1
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "$Project_Id"
