name: "Action"
on:
  pull_request:
    branches:
      - master
    paths:
      - 'vars/project-1/c1.txt'
  push:
    branches:
      - master
    paths:
      - 'vars/project-1/c1.txt'
env:
  Project_Id: project-345
  Cluster_name: c1
jobs:
  call-workflow:
    uses: ./.github/workflows/called.yml
    with:
      Project_Id: $Project_Id
    secrets: inherit
