name : 'Test'
on:
  workflow_call:
    inputs:
      Project_Id:
        required: true
        type: string
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
             echo ${{inputs.Project_Id}}
             #echo ${{ secrets.SECRET_1 }}
             
