name: "Action"
on:
  pull_request:
    branches:
      - master
    paths:
      - 'vars/project-1/c1.txt'
  push:
    branches:
      - test
    paths:
      - 'vars/project-1/c1.txt'
jobs:
  call-workflow:
    uses: ./.github/workflows/calledtest.yml
    with:
      Project_Id: project-1
    secrets: inherit
