name: "Action"
on:
  pull_request:
    branches:
      - master
    paths:
      - 'vars/project-2/c1.txt'
  push:
    branches:
      - master
    paths:
      - 'vars/project-2/c1.txt'
jobs:
  call-workflow:
    uses: ./.github/workflows/called.yml
    with:
      Project_Id: project-2
    secrets: inherit
